# Generated by Django 5.2 on 2025-06-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginfo', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(default=999999999),
            preserve_default=False,
        ),
    ]
