# Generated by Django 5.2 on 2025-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_Id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
