# Generated by Django 5.2 on 2025-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Payment_Method',
            field=models.CharField(choices=[('COD', 'cash on delivery'), ('online payment', 'online payment')], max_length=100),
        ),
    ]
